import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import PullToRefresh from "@/components/ui/PullToRefresh";
import MobileSelect from "@/components/ui/MobileSelect";
import ConfirmDialog from "@/components/ui/ConfirmDialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, TrendingUp, TrendingDown, Banknote } from "lucide-react";
import FinanceForm from "@/components/finance/FinanceForm";
import FinanceTable from "@/components/finance/FinanceTable";
import MonthlySummary from "@/components/finance/MonthlySummary";
import { format } from "date-fns";
import { es } from "date-fns/locale";

function parseLocalDate(str) {
  if (!str) return null;
  const [y, m, d] = str.split("-").map(Number);
  return new Date(y, m - 1, d);
}
import { removePaidToday } from "@/lib/paidToday";

// Detect type of auto-generated record from description
function getAutoType(item) {
  if (!item?.description) return null;
  const desc = item.description.toLowerCase();
  if (desc.includes("pago planilla") || desc.startsWith("planilla")) return "planilla";
  if (desc.includes("vacaciones")) return "vacaciones";
  if (desc.includes("descuento") || desc.includes("adelanto")) return "deduccion";
  if (desc.includes("gasto fijo")) return "gasto_fijo";
  return null;
}

function isAutoGenerated(item) {
  return getAutoType(item) !== null;
}

// Extract worker name from descriptions like:
// "Pago planilla (mensual) — NombreTrabajador"
// "Vacaciones — NombreTrabajador (detalle)"
function extractWorkerName(description) {
  // Match text after "— " and before optional " (" parenthesis
  const match = description?.match(/—\s*([^(]+)/);
  return match ? match[1].trim() : null;
}

function getAvailableMonths(items) {
  const set = new Set();
  items.forEach((i) => { if (i.date) set.add(i.date.substring(0, 7)); });
  return [...set].sort().reverse();
}

export default function Finances() {
  const [formOpen, setFormOpen] = useState(false);
  const [formType, setFormType] = useState("income");
  const [editing, setEditing] = useState(null);
  const [confirmState, setConfirmState] = useState(null);
  const [selectedMonth, setSelectedMonth] = useState(() => {
    // Default to current month so new payments are always visible
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
  });
  const queryClient = useQueryClient();

  const { data: incomes = [] } = useQuery({
    queryKey: ["incomes"],
    queryFn: () => base44.entities.Income.list("-created_date", 500),
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: "always",
  });

  const { data: expenses = [] } = useQuery({
    queryKey: ["expenses"],
    queryFn: () => base44.entities.Expense.list("-created_date", 500),
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: "always",
    refetchOnWindowFocus: true,
  });

  const { data: workers = [] } = useQuery({
    queryKey: ["workers"],
    queryFn: () => base44.entities.Worker.list(),
  });

  const { data: deductions = [] } = useQuery({
    queryKey: ["deductions"],
    queryFn: () => base44.entities.Deduction.list(),
  });

  const { data: fixedExpPayments = [] } = useQuery({
    queryKey: ["fixedExpPayments"],
    queryFn: () => base44.entities.FixedExpensePayment.list("-created_date"),
  });

  const { data: fixedExpenses = [] } = useQuery({
    queryKey: ["fixedExpenses"],
    queryFn: () => base44.entities.FixedExpense.list(),
  });

  // Force refetch every time the user returns to this page (tab focus or navigation)
  useEffect(() => {
    const refetchAll = () => {
      queryClient.invalidateQueries({ queryKey: ["expenses"], refetchType: "all" });
      queryClient.invalidateQueries({ queryKey: ["incomes"], refetchType: "all" });
    };
    // Refetch immediately on mount
    refetchAll();
    // Also refetch when the browser tab becomes visible again
    const onVisible = () => { if (document.visibilityState === "visible") refetchAll(); };
    document.addEventListener("visibilitychange", onVisible);
    return () => document.removeEventListener("visibilitychange", onVisible);
  }, [queryClient]);

  // Real-time subscriptions: jump to the month of the new record when on the page
  useEffect(() => {
    const unsubExpense = base44.entities.Expense.subscribe((event) => {
      queryClient.invalidateQueries({ queryKey: ["expenses"] });
      if (event.type === "create" && event.data?.date) {
        setSelectedMonth(event.data.date.substring(0, 7));
      }
    });
    const unsubIncome = base44.entities.Income.subscribe((event) => {
      queryClient.invalidateQueries({ queryKey: ["incomes"] });
      if (event.type === "create" && event.data?.date) {
        setSelectedMonth(event.data.date.substring(0, 7));
      }
    });
    return () => { unsubExpense(); unsubIncome(); };
  }, [queryClient]);

  const deleteFixedExpPayment = useMutation({
    mutationFn: (id) => base44.entities.FixedExpensePayment.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["fixedExpPayments"] }),
  });

  const updateWorker = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Worker.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["workers"] }),
  });

  const updateDeduction = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Deduction.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["deductions"] }),
  });

  const createIncome = useMutation({
    mutationFn: (data) => base44.entities.Income.create(data),
    onMutate: async (data) => {
      await queryClient.cancelQueries({ queryKey: ["incomes"] });
      const prev = queryClient.getQueryData(["incomes"]) || [];
      const temp = { ...data, id: "temp-" + Date.now() };
      queryClient.setQueryData(["incomes"], [temp, ...prev]);
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["incomes"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const updateIncome = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Income.update(id, data),
    onMutate: async ({ id, data }) => {
      await queryClient.cancelQueries({ queryKey: ["incomes"] });
      const prev = queryClient.getQueryData(["incomes"]) || [];
      queryClient.setQueryData(["incomes"], prev.map(i => i.id === id ? { ...i, ...data } : i));
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["incomes"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const deleteIncome = useMutation({
    mutationFn: (id) => base44.entities.Income.delete(id),
    onMutate: async (id) => {
      await queryClient.cancelQueries({ queryKey: ["incomes"] });
      const prev = queryClient.getQueryData(["incomes"]) || [];
      queryClient.setQueryData(["incomes"], prev.filter(i => i.id !== id));
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["incomes"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });

  const createExpense = useMutation({
    mutationFn: (data) => base44.entities.Expense.create(data),
    onMutate: async (data) => {
      await queryClient.cancelQueries({ queryKey: ["expenses"] });
      const prev = queryClient.getQueryData(["expenses"]) || [];
      const temp = { ...data, id: "temp-" + Date.now() };
      queryClient.setQueryData(["expenses"], [temp, ...prev]);
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["expenses"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const updateExpense = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Expense.update(id, data),
    onMutate: async ({ id, data }) => {
      await queryClient.cancelQueries({ queryKey: ["expenses"] });
      const prev = queryClient.getQueryData(["expenses"]) || [];
      queryClient.setQueryData(["expenses"], prev.map(e => e.id === id ? { ...e, ...data } : e));
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["expenses"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const deleteExpense = useMutation({
    mutationFn: (id) => base44.entities.Expense.delete(id),
    onMutate: async (id) => {
      await queryClient.cancelQueries({ queryKey: ["expenses"] });
      const prev = queryClient.getQueryData(["expenses"]) || [];
      queryClient.setQueryData(["expenses"], prev.filter(e => e.id !== id));
      return { prev };
    },
    onError: (_e, _v, ctx) => queryClient.setQueryData(["expenses"], ctx.prev),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });

  const handleSubmit = (data) => {
    if (formType === "income") {
      editing ? updateIncome.mutate({ id: editing.id, data }) : createIncome.mutate(data);
    } else {
      editing ? updateExpense.mutate({ id: editing.id, data }) : createExpense.mutate(data);
    }
    setEditing(null);
  };

  const openForm = (type) => { setFormType(type); setEditing(null); setFormOpen(true); };
  const handleEdit = (item, type) => { setFormType(type); setEditing(item); setFormOpen(true); };

  // Revert associated state when deleting an auto-generated record
  const revertAutoRecord = (item) => {
    const autoType = getAutoType(item);
    const workerName = extractWorkerName(item.description);

    if (autoType === "planilla" && workerName) {
      const worker = workers.find((w) => w.name === workerName);
      if (worker) {
        // Remove from paidToday so button resets
        removePaidToday("planilla", worker.id);
        // Revert last paid installment for each active deduction of this worker
        const workerDeds = deductions.filter((d) => d.worker_id === worker.id && (d.paid_installments || 0) > 0);
        for (const ded of workerDeds) {
          const newPaid = ded.paid_installments - 1;
          updateDeduction.mutate({
            id: ded.id,
            data: { ...ded, paid_installments: newPaid, status: newPaid === 0 ? "pendiente" : "en_proceso" },
          });
        }
        queryClient.invalidateQueries({ queryKey: ["workers"] });
      }
    }

    if (autoType === "vacaciones" && workerName) {
      const worker = workers.find((w) => w.name === workerName);
      if (worker) {
        updateWorker.mutate({ id: worker.id, data: { ...worker, vacation_paid_date: null } });
        removePaidToday("vacaciones", worker.id);
      }
    }

    if (autoType === "gasto_fijo") {
      // Extract description like "Gasto fijo — ItemDescription (Company)"
      const descMatch = item.description?.match(/Gasto fijo\s*—\s*(.+?)(?:\s*\(|$)/);
      const fixedDesc = descMatch ? descMatch[1].trim() : null;
      if (fixedDesc) {
        const fe = fixedExpenses.find((f) => f.description === fixedDesc);
        if (fe) {
          // Delete the most recent FixedExpensePayment for this item
          const relatedPayments = fixedExpPayments.filter((p) => p.fixed_expense_id === fe.id);
          if (relatedPayments.length > 0) {
            const latest = relatedPayments.sort((a, b) => b.payment_date?.localeCompare(a.payment_date))[0];
            deleteFixedExpPayment.mutate(latest.id);
          }
          removePaidToday("gastos_fijos", fe.id);
        }
      }
    }

    if (autoType === "deduccion" && workerName) {
      // Revert last paid installment for matching deductions
      const workerObj = workers.find((w) => w.name === workerName);
      if (workerObj) {
        const workerDeds = deductions.filter((d) => d.worker_id === workerObj.id && d.paid_installments > 0);
        // Revert the most recently paid one
        const lastPaid = workerDeds.sort((a, b) => b.paid_installments - a.paid_installments)[0];
        if (lastPaid) {
          const newPaid = lastPaid.paid_installments - 1;
          updateDeduction.mutate({ id: lastPaid.id, data: { ...lastPaid, paid_installments: newPaid, status: newPaid === 0 ? "pendiente" : "en_proceso" } });
        }
      }
    }
  };

  const handleDeleteExpense = (item) => {
    const autoType = getAutoType(item);
    if (autoType) {
      const revertMsg = autoType === "planilla"
        ? "El estado de pago del trabajador será revertido (podrá volver a pagarse) y se revertirá la última cuota de sus descuentos/adelantos activos."
        : autoType === "vacaciones"
        ? "Las vacaciones del trabajador serán revertidas."
        : autoType === "deduccion"
        ? "Se revertirá la última cuota del descuento/adelanto del trabajador."
        : autoType === "gasto_fijo"
        ? "Se revertirá el pago del gasto fijo (podrá volver a pagarse)."
        : "Solo se eliminará el registro contable.";
      setConfirmState({
        title: "¿Eliminar registro automático?",
        description: `Este gasto fue generado automáticamente:\n"${item.description}"\n\n✅ ${revertMsg}`,
        onConfirm: () => { revertAutoRecord(item); deleteExpense.mutate(item.id); },
      });
      return;
    }
    setConfirmState({
      title: "¿Eliminar gasto?",
      description: `Se eliminará el gasto "${item.description}" del ${item.date || ""}. Esta acción no se puede deshacer.`,
      onConfirm: () => deleteExpense.mutate(item.id),
    });
  };

  const handleDeleteIncome = (item) => {
    if (isAutoGenerated(item)) {
      setConfirmState({
        title: "¿Eliminar ingreso automático?",
        description: `Este ingreso fue generado automáticamente:\n"${item.description}"\n\n⚠️ Solo se eliminará el registro contable.`,
        onConfirm: () => deleteIncome.mutate(item.id),
      });
      return;
    }
    setConfirmState({
      title: "¿Eliminar ingreso?",
      description: `Se eliminará el ingreso "${item.description}" del ${item.date || ""}. Esta acción no se puede deshacer.`,
      onConfirm: () => deleteIncome.mutate(item.id),
    });
  };

  // All unique months from both lists
  const allMonths = [...new Set([
    ...getAvailableMonths(incomes),
    ...getAvailableMonths(expenses),
  ])].sort().reverse();

  const filteredIncomes = selectedMonth === "all"
    ? incomes
    : incomes.filter((i) => i.date?.startsWith(selectedMonth));

  const filteredExpenses = selectedMonth === "all"
    ? expenses
    : expenses.filter((e) => e.date?.startsWith(selectedMonth));

  const monthOptions = [
    { value: "all", label: "Todos los meses" },
    ...allMonths.map((m) => ({ value: m, label: format(parseLocalDate(m + "-02"), "MMMM yyyy", { locale: es }) })),
  ];

  const handleRefresh = () => {
    queryClient.invalidateQueries({ queryKey: ["expenses"], refetchType: "all" });
    queryClient.invalidateQueries({ queryKey: ["incomes"], refetchType: "all" });
  };

  return (
    <PullToRefresh onRefresh={handleRefresh}>
    <div className="space-y-6 max-w-7xl mx-auto p-4 lg:p-0">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold tracking-tight">Ingresos y Gastos</h1>
          <p className="text-muted-foreground mt-1">Control financiero con historial por mes</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button onClick={() => openForm("income")} className="gap-2 bg-emerald-600 hover:bg-emerald-700">
            <Plus className="w-4 h-4" /> Ingreso
          </Button>
          <Button onClick={() => openForm("expense")} variant="destructive" className="gap-2">
            <Plus className="w-4 h-4" /> Gasto
          </Button>
        </div>
      </div>

      {/* Month filter */}
      <div className="flex items-center gap-3">
        <span className="text-sm font-medium text-muted-foreground">Filtrar por mes:</span>
        <MobileSelect
          value={selectedMonth}
          onValueChange={setSelectedMonth}
          options={monthOptions}
          placeholder="Todos los meses"
          label="Filtrar por mes"
          triggerClassName="w-48"
        />
      </div>

      {/* Recuadro: Gastos en efectivo del día */}
      {(() => {
        const todayStr = (() => {
          const d = new Date();
          return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
        })();
        const cashToday = expenses.filter(e => e.date === todayStr && (e.payment_method === "efectivo" || !e.payment_method));
        const cashTotal = cashToday.reduce((sum, e) => sum + (e.amount || 0), 0);
        return (
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 flex items-center gap-4">
            <div className="w-11 h-11 rounded-xl bg-amber-100 flex items-center justify-center shrink-0">
              <Banknote className="w-5 h-5 text-amber-600" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-xs text-amber-700 font-medium uppercase tracking-wide">Gastos en Efectivo — Hoy</p>
              <p className="text-2xl font-bold text-amber-800">
                {new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(cashTotal)}
              </p>
              <p className="text-xs text-amber-600">{cashToday.length} gasto{cashToday.length !== 1 ? "s" : ""} en efectivo registrado{cashToday.length !== 1 ? "s" : ""} hoy</p>
            </div>
          </div>
        );
      })()}

      <MonthlySummary incomes={filteredIncomes} expenses={filteredExpenses} />

      <Tabs defaultValue="incomes">
        <TabsList className="mb-4">
          <TabsTrigger value="incomes" className="gap-2">
            <TrendingUp className="w-4 h-4" /> Ingresos ({filteredIncomes.length})
          </TabsTrigger>
          <TabsTrigger value="expenses" className="gap-2">
            <TrendingDown className="w-4 h-4" /> Gastos ({filteredExpenses.length})
          </TabsTrigger>
        </TabsList>
        <TabsContent value="incomes">
          <FinanceTable
            items={filteredIncomes}
            type="income"
            onEdit={(item) => handleEdit(item, "income")}
            onDelete={(id, item) => handleDeleteIncome(item || incomes.find(i => i.id === id) || { id })}
          />
        </TabsContent>
        <TabsContent value="expenses">
          <FinanceTable
            items={filteredExpenses}
            type="expense"
            onEdit={(item) => handleEdit(item, "expense")}
            onDelete={(id, item) => handleDeleteExpense(item || expenses.find(e => e.id === id) || { id })}
          />
        </TabsContent>
      </Tabs>

      <FinanceForm
        open={formOpen}
        onClose={() => { setFormOpen(false); setEditing(null); }}
        onSubmit={handleSubmit}
        type={formType}
        editing={editing}
      />
      <ConfirmDialog
        open={!!confirmState}
        onOpenChange={(o) => { if (!o) setConfirmState(null); }}
        title={confirmState?.title}
        description={confirmState?.description}
        onConfirm={() => { confirmState?.onConfirm(); setConfirmState(null); }}
        confirmLabel="Eliminar"
        destructive
      />
    </div>
    </PullToRefresh>
  );
}