import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, TrendingUp, TrendingDown } from "lucide-react";
import FinanceForm from "@/components/finance/FinanceForm";
import FinanceTable from "@/components/finance/FinanceTable";
import MonthlySummary from "@/components/finance/MonthlySummary";
import { format } from "date-fns";
import { es } from "date-fns/locale";

// Auto-sources that should revert when deleted
const AUTO_SOURCE_PATTERNS = [
  "pago planilla", "vacaciones", "gasto fijo", "planilla", "descuento", "adelanto"
];

function isAutoGenerated(item) {
  if (!item?.description) return false;
  const desc = item.description.toLowerCase();
  return AUTO_SOURCE_PATTERNS.some((p) => desc.includes(p));
}

function getAvailableMonths(items) {
  const set = new Set();
  items.forEach((i) => { if (i.date) set.add(i.date.substring(0, 7)); });
  return [...set].sort().reverse();
}

export default function Finances() {
  const [formOpen, setFormOpen] = useState(false);
  const [formType, setFormType] = useState("income");
  const [editing, setEditing] = useState(null);
  const [selectedMonth, setSelectedMonth] = useState("all");
  const queryClient = useQueryClient();

  const { data: incomes = [] } = useQuery({
    queryKey: ["incomes"],
    queryFn: () => base44.entities.Income.list("-date"),
  });

  const { data: expenses = [] } = useQuery({
    queryKey: ["expenses"],
    queryFn: () => base44.entities.Expense.list("-date"),
  });

  const createIncome = useMutation({
    mutationFn: (data) => base44.entities.Income.create(data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const updateIncome = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Income.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const deleteIncome = useMutation({
    mutationFn: (id) => base44.entities.Income.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });

  const createExpense = useMutation({
    mutationFn: (data) => base44.entities.Expense.create(data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const updateExpense = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Expense.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const deleteExpense = useMutation({
    mutationFn: (id) => base44.entities.Expense.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });

  const handleSubmit = (data) => {
    if (formType === "income") {
      editing ? updateIncome.mutate({ id: editing.id, data }) : createIncome.mutate(data);
    } else {
      editing ? updateExpense.mutate({ id: editing.id, data }) : createExpense.mutate(data);
    }
    setEditing(null);
  };

  const openForm = (type) => { setFormType(type); setEditing(null); setFormOpen(true); };
  const handleEdit = (item, type) => { setFormType(type); setEditing(item); setFormOpen(true); };

  // Delete with auto-source warning
  const handleDeleteExpense = (item) => {
    if (isAutoGenerated(item)) {
      const confirmed = window.confirm(
        `Este gasto fue generado automáticamente desde: "${item.description}".\n\n⚠️ Solo se eliminará el registro contable. El estado del trabajador en planilla deberá ajustarse manualmente si es necesario.\n\n¿Deseas continuar?`
      );
      if (!confirmed) return;
    }
    deleteExpense.mutate(item.id);
  };

  const handleDeleteIncome = (item) => {
    if (isAutoGenerated(item)) {
      const confirmed = window.confirm(
        `Este ingreso fue generado automáticamente: "${item.description}".\n\n⚠️ Solo se eliminará el registro contable.\n\n¿Deseas continuar?`
      );
      if (!confirmed) return;
    }
    deleteIncome.mutate(item.id);
  };

  // All unique months from both lists
  const allMonths = [...new Set([
    ...getAvailableMonths(incomes),
    ...getAvailableMonths(expenses),
  ])].sort().reverse();

  const filteredIncomes = selectedMonth === "all"
    ? incomes
    : incomes.filter((i) => i.date?.startsWith(selectedMonth));

  const filteredExpenses = selectedMonth === "all"
    ? expenses
    : expenses.filter((e) => e.date?.startsWith(selectedMonth));

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold tracking-tight">Ingresos y Gastos</h1>
          <p className="text-muted-foreground mt-1">Control financiero con historial por mes</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button onClick={() => openForm("income")} className="gap-2 bg-emerald-600 hover:bg-emerald-700">
            <Plus className="w-4 h-4" /> Ingreso
          </Button>
          <Button onClick={() => openForm("expense")} variant="destructive" className="gap-2">
            <Plus className="w-4 h-4" /> Gasto
          </Button>
        </div>
      </div>

      {/* Month filter */}
      <div className="flex items-center gap-3">
        <span className="text-sm font-medium text-muted-foreground">Filtrar por mes:</span>
        <Select value={selectedMonth} onValueChange={setSelectedMonth}>
          <SelectTrigger className="w-48">
            <SelectValue placeholder="Todos los meses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Todos los meses</SelectItem>
            {allMonths.map((m) => (
              <SelectItem key={m} value={m}>
                {format(new Date(m + "-02"), "MMMM yyyy", { locale: es })}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <MonthlySummary incomes={filteredIncomes} expenses={filteredExpenses} />

      <Tabs defaultValue="incomes">
        <TabsList className="mb-4">
          <TabsTrigger value="incomes" className="gap-2">
            <TrendingUp className="w-4 h-4" /> Ingresos ({filteredIncomes.length})
          </TabsTrigger>
          <TabsTrigger value="expenses" className="gap-2">
            <TrendingDown className="w-4 h-4" /> Gastos ({filteredExpenses.length})
          </TabsTrigger>
        </TabsList>
        <TabsContent value="incomes">
          <FinanceTable
            items={filteredIncomes}
            type="income"
            onEdit={(item) => handleEdit(item, "income")}
            onDelete={(id, item) => handleDeleteIncome(item || incomes.find(i => i.id === id) || { id })}
          />
        </TabsContent>
        <TabsContent value="expenses">
          <FinanceTable
            items={filteredExpenses}
            type="expense"
            onEdit={(item) => handleEdit(item, "expense")}
            onDelete={(id, item) => handleDeleteExpense(item || expenses.find(e => e.id === id) || { id })}
          />
        </TabsContent>
      </Tabs>

      <FinanceForm
        open={formOpen}
        onClose={() => { setFormOpen(false); setEditing(null); }}
        onSubmit={handleSubmit}
        type={formType}
        editing={editing}
      />
    </div>
  );
}