import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, TrendingUp, TrendingDown } from "lucide-react";
import FinanceForm from "@/components/finance/FinanceForm";
import FinanceTable from "@/components/finance/FinanceTable";
import MonthlySummary from "@/components/finance/MonthlySummary";
import { format } from "date-fns";
import { es } from "date-fns/locale";
import { removePaidToday } from "@/lib/paidToday";

// Detect type of auto-generated record from description
function getAutoType(item) {
  if (!item?.description) return null;
  const desc = item.description.toLowerCase();
  if (desc.includes("pago planilla") || desc.startsWith("planilla")) return "planilla";
  if (desc.includes("vacaciones")) return "vacaciones";
  if (desc.includes("descuento") || desc.includes("adelanto")) return "deduccion";
  if (desc.includes("gasto fijo")) return "gasto_fijo";
  return null;
}

function isAutoGenerated(item) {
  return getAutoType(item) !== null;
}

// Extract worker name from descriptions like:
// "Pago planilla (mensual) — NombreTrabajador"
// "Vacaciones — NombreTrabajador (detalle)"
function extractWorkerName(description) {
  // Match text after "— " and before optional " (" parenthesis
  const match = description?.match(/—\s*([^(]+)/);
  return match ? match[1].trim() : null;
}

function getAvailableMonths(items) {
  const set = new Set();
  items.forEach((i) => { if (i.date) set.add(i.date.substring(0, 7)); });
  return [...set].sort().reverse();
}

export default function Finances() {
  const [formOpen, setFormOpen] = useState(false);
  const [formType, setFormType] = useState("income");
  const [editing, setEditing] = useState(null);
  const [selectedMonth, setSelectedMonth] = useState("all");
  const queryClient = useQueryClient();

  const { data: incomes = [] } = useQuery({
    queryKey: ["incomes"],
    queryFn: () => base44.entities.Income.list("-date"),
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: "always",
  });

  const { data: expenses = [] } = useQuery({
    queryKey: ["expenses"],
    queryFn: () => base44.entities.Expense.list("-date"),
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: "always",
  });

  const { data: workers = [] } = useQuery({
    queryKey: ["workers"],
    queryFn: () => base44.entities.Worker.list(),
  });

  const { data: deductions = [] } = useQuery({
    queryKey: ["deductions"],
    queryFn: () => base44.entities.Deduction.list(),
  });

  const { data: fixedExpPayments = [] } = useQuery({
    queryKey: ["fixedExpPayments"],
    queryFn: () => base44.entities.FixedExpensePayment.list("-created_date"),
  });

  const { data: fixedExpenses = [] } = useQuery({
    queryKey: ["fixedExpenses"],
    queryFn: () => base44.entities.FixedExpense.list(),
  });

  const deleteFixedExpPayment = useMutation({
    mutationFn: (id) => base44.entities.FixedExpensePayment.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["fixedExpPayments"] }),
  });

  const updateWorker = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Worker.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["workers"] }),
  });

  const updateDeduction = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Deduction.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["deductions"] }),
  });

  const createIncome = useMutation({
    mutationFn: (data) => base44.entities.Income.create(data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const updateIncome = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Income.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });
  const deleteIncome = useMutation({
    mutationFn: (id) => base44.entities.Income.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["incomes"] }),
  });

  const createExpense = useMutation({
    mutationFn: (data) => base44.entities.Expense.create(data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const updateExpense = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Expense.update(id, data),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });
  const deleteExpense = useMutation({
    mutationFn: (id) => base44.entities.Expense.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["expenses"] }),
  });

  const handleSubmit = (data) => {
    if (formType === "income") {
      editing ? updateIncome.mutate({ id: editing.id, data }) : createIncome.mutate(data);
    } else {
      editing ? updateExpense.mutate({ id: editing.id, data }) : createExpense.mutate(data);
    }
    setEditing(null);
  };

  const openForm = (type) => { setFormType(type); setEditing(null); setFormOpen(true); };
  const handleEdit = (item, type) => { setFormType(type); setEditing(item); setFormOpen(true); };

  // Revert associated state when deleting an auto-generated record
  const revertAutoRecord = (item) => {
    const autoType = getAutoType(item);
    const workerName = extractWorkerName(item.description);

    if (autoType === "planilla" && workerName) {
      const worker = workers.find((w) => w.name === workerName);
      if (worker) {
        // Remove from paidToday so button resets
        removePaidToday("planilla", worker.id);
        // Revert last paid installment for each active deduction of this worker
        const workerDeds = deductions.filter((d) => d.worker_id === worker.id && (d.paid_installments || 0) > 0);
        for (const ded of workerDeds) {
          const newPaid = ded.paid_installments - 1;
          updateDeduction.mutate({
            id: ded.id,
            data: { ...ded, paid_installments: newPaid, status: newPaid === 0 ? "pendiente" : "en_proceso" },
          });
        }
        queryClient.invalidateQueries({ queryKey: ["workers"] });
      }
    }

    if (autoType === "vacaciones" && workerName) {
      const worker = workers.find((w) => w.name === workerName);
      if (worker) {
        updateWorker.mutate({ id: worker.id, data: { ...worker, vacation_paid_date: null } });
        removePaidToday("vacaciones", worker.id);
      }
    }

    if (autoType === "gasto_fijo") {
      // Extract description like "Gasto fijo — ItemDescription (Company)"
      const descMatch = item.description?.match(/Gasto fijo\s*—\s*(.+?)(?:\s*\(|$)/);
      const fixedDesc = descMatch ? descMatch[1].trim() : null;
      if (fixedDesc) {
        const fe = fixedExpenses.find((f) => f.description === fixedDesc);
        if (fe) {
          // Delete the most recent FixedExpensePayment for this item
          const relatedPayments = fixedExpPayments.filter((p) => p.fixed_expense_id === fe.id);
          if (relatedPayments.length > 0) {
            const latest = relatedPayments.sort((a, b) => b.payment_date?.localeCompare(a.payment_date))[0];
            deleteFixedExpPayment.mutate(latest.id);
          }
          removePaidToday("gastos_fijos", fe.id);
        }
      }
    }

    if (autoType === "deduccion" && workerName) {
      // Revert last paid installment for matching deductions
      const workerObj = workers.find((w) => w.name === workerName);
      if (workerObj) {
        const workerDeds = deductions.filter((d) => d.worker_id === workerObj.id && d.paid_installments > 0);
        // Revert the most recently paid one
        const lastPaid = workerDeds.sort((a, b) => b.paid_installments - a.paid_installments)[0];
        if (lastPaid) {
          const newPaid = lastPaid.paid_installments - 1;
          updateDeduction.mutate({ id: lastPaid.id, data: { ...lastPaid, paid_installments: newPaid, status: newPaid === 0 ? "pendiente" : "en_proceso" } });
        }
      }
    }
  };

  const handleDeleteExpense = (item) => {
    const autoType = getAutoType(item);
    if (autoType) {
      const revertMsg = autoType === "planilla"
        ? "El estado de pago del trabajador será revertido (podrá volver a pagarse) y se revertirá la última cuota de sus descuentos/adelantos activos."
        : autoType === "vacaciones"
        ? "Las vacaciones del trabajador serán revertidas."
        : autoType === "deduccion"
        ? "Se revertirá la última cuota del descuento/adelanto del trabajador."
        : autoType === "gasto_fijo"
        ? "Se revertirá el pago del gasto fijo (podrá volver a pagarse)."
        : "Solo se eliminará el registro contable.";

      const confirmed = window.confirm(
        `Este gasto fue generado automáticamente: "${item.description}".\n\n✅ ${revertMsg}\n\n¿Deseas continuar?`
      );
      if (!confirmed) return;
      revertAutoRecord(item);
    }
    deleteExpense.mutate(item.id);
  };

  const handleDeleteIncome = (item) => {
    if (isAutoGenerated(item)) {
      const confirmed = window.confirm(
        `Este ingreso fue generado automáticamente: "${item.description}".\n\n⚠️ Solo se eliminará el registro contable.\n\n¿Deseas continuar?`
      );
      if (!confirmed) return;
    }
    deleteIncome.mutate(item.id);
  };

  // All unique months from both lists
  const allMonths = [...new Set([
    ...getAvailableMonths(incomes),
    ...getAvailableMonths(expenses),
  ])].sort().reverse();

  const filteredIncomes = selectedMonth === "all"
    ? incomes
    : incomes.filter((i) => i.date?.startsWith(selectedMonth));

  const filteredExpenses = selectedMonth === "all"
    ? expenses
    : expenses.filter((e) => e.date?.startsWith(selectedMonth));

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold tracking-tight">Ingresos y Gastos</h1>
          <p className="text-muted-foreground mt-1">Control financiero con historial por mes</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button onClick={() => openForm("income")} className="gap-2 bg-emerald-600 hover:bg-emerald-700">
            <Plus className="w-4 h-4" /> Ingreso
          </Button>
          <Button onClick={() => openForm("expense")} variant="destructive" className="gap-2">
            <Plus className="w-4 h-4" /> Gasto
          </Button>
        </div>
      </div>

      {/* Month filter */}
      <div className="flex items-center gap-3">
        <span className="text-sm font-medium text-muted-foreground">Filtrar por mes:</span>
        <Select value={selectedMonth} onValueChange={setSelectedMonth}>
          <SelectTrigger className="w-48">
            <SelectValue placeholder="Todos los meses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Todos los meses</SelectItem>
            {allMonths.map((m) => (
              <SelectItem key={m} value={m}>
                {format(new Date(m + "-02"), "MMMM yyyy", { locale: es })}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <MonthlySummary incomes={filteredIncomes} expenses={filteredExpenses} />

      <Tabs defaultValue="incomes">
        <TabsList className="mb-4">
          <TabsTrigger value="incomes" className="gap-2">
            <TrendingUp className="w-4 h-4" /> Ingresos ({filteredIncomes.length})
          </TabsTrigger>
          <TabsTrigger value="expenses" className="gap-2">
            <TrendingDown className="w-4 h-4" /> Gastos ({filteredExpenses.length})
          </TabsTrigger>
        </TabsList>
        <TabsContent value="incomes">
          <FinanceTable
            items={filteredIncomes}
            type="income"
            onEdit={(item) => handleEdit(item, "income")}
            onDelete={(id, item) => handleDeleteIncome(item || incomes.find(i => i.id === id) || { id })}
          />
        </TabsContent>
        <TabsContent value="expenses">
          <FinanceTable
            items={filteredExpenses}
            type="expense"
            onEdit={(item) => handleEdit(item, "expense")}
            onDelete={(id, item) => handleDeleteExpense(item || expenses.find(e => e.id === id) || { id })}
          />
        </TabsContent>
      </Tabs>

      <FinanceForm
        open={formOpen}
        onClose={() => { setFormOpen(false); setEditing(null); }}
        onSubmit={handleSubmit}
        type={formType}
        editing={editing}
      />
    </div>
  );
}